### ISSUE TITLE
Date formatter bug in visits_after

### ISSUE THREAD

**Issue by elliottwilliams** [propershark/timetable_cpp#17]
I'm seeing malformed dates on calls to visits_after:

`timetable.visits_after(BUS064, 20170330 17:18:55, 5) => `
```
[ [ '20170330 00:17344',
    '20170330 00:17792',
    '28',
    'to/from Purdue Village & Dorms & Campus' ],
  [ '20170330 00:17344',
    '20170330 00:17792',
    '28',
    'to/from Purdue Village & Dorms & Campus' ],
  [ '20170330 00:17344',
    '20170330 00:17792',
    '28',
    'to/from Purdue Village & Dorms & Campus' ],
  [ '20170330 00:17344',
    '20170330 00:17792',
    '28',
    'to/from Purdue Village & Dorms & Campus' ],
  [ '20170330 00:17344',
    '20170330 00:17792',
    '28',
    'to/from Purdue Village & Dorms & Campus' ] ]
```

A comparable call to visits_between (with expected dates), is:

`timetable.visits_between(BUS064, 20170330 17:18:55, 20170330 18:18:55, 5) => `
```
[ [ '20170330 17:24:00',
    '20170330 17:24:00',
    '28',
    'to/from Purdue Village & Dorms & Campus' ],
  [ '20170330 17:36:00',
    '20170330 17:36:00',
    '28',
    'to/from Purdue Village & Dorms & Campus' ],
  [ '20170330 17:48:00',
    '20170330 17:48:00',
    '28',
    'to/from Purdue Village & Dorms & Campus' ],
  [ '20170330 18:00:00',
    '20170330 18:00:00',
    '28',
    'to/from Purdue Village & Dorms & Campus' ],
  [ '20170330 18:12:00',
    '20170330 18:12:00',
    '28',
    'to/from Purdue Village & Dorms & Campus' ] ]
```

I should note that I'm switching to visits_after for the [POI view][1] — since the view is supposed to refresh itself with new arrivals as old ones depart, I now call visits_after periodically and filter what is displayed in the client to only show the next hour.

[1]: https://github.com/propershark/proper/issues/10

**Comment by faultyserver** [comment]
FWIW, [`visits_after` isn't currently implemented on master](https://github.com/propershark/timetable_cpp/blob/master/src/timetable/visits_after.cc#L4) :)

I'm not entirely sure how the times would have overflowed like that, but I'm hoping that when the real implementation does happen it won't exist. I'll leave this open until that happens in case this comes back.

**Comment by faultyserver** [comment]
I did a little bit of looking at what the old implementation was like. The most recent one just [reused the date portion of the original request](https://github.com/propershark/timetable_cpp/blob/9866bfe757fd428cfac0794d23225f6dd4789263/src/timetable/visits_after.cc#L13).

`DateTime#date()` technically returns a string, but DateTimes can also be initialized from strings. The result was that the `Visit` constructor that is implicitly called on that line (which expects DateTime parameters) re-converts the string to a DateTime using the single-argument constructor.

That constructor, however, expects the string to contain both a Date and a Time part. Because it only contains the date part, the time fields are left uninitialized. While the `%2d` flags used when formatting the time part should enforce the `00:00:00` formatting, I wouldn't be surprised if the garbage values are somehow ignoring the `2` width specifier.

`visits_between` still works because it [doesn't do those redundant `DateTime -> string -> DateTime` conversions](https://github.com/propershark/timetable_cpp/blob/master/src/timetable/visits_between.cc#L24), so there aren't any garbage values in the time fields.

Again, this is all irrelevant at this point, since the implementation is gone now and needs to be re-written anyway.

**Comment by faultyserver** [comment]
@elliottwilliams I just pushed up proper implementations for the entire `visits_*` family of functions. Can you test and see if this is fixed?

P.S. I haven't done any testing on them myself, so it's possible they may not be registered properly with WAMP.

**Comment by faultyserver** [comment]
I did some more local testing and it seems like this is indeed fixed, but I'll wait for confirmation before closing.

**Comment by elliottwilliams** [comment]
Confirmed.
