### ISSUE TITLE
Create visits RPCs for all routes at a station

### ISSUE THREAD

**Issue by elliottwilliams** [propershark/timetable_cpp#3]
As discussed on January 15:

> emw - Last Sunday at 10:24 AM
> Another thing I'm realizing is that there are some instances where I'd rather get all arrivals on a station, regardless of route, in order
> I can multiplex different next_visits calls together, but it'd be simpler to just ask for the n next visits from Timetable. It'd also prevent me from having to know the associated routes for a station before making the call.
> If either of these things seem reasonable to you, btw, I can create an issue
> 
> faulty - Last Sunday at 11:34 AM
> I sort of bundled this into my response on the same issue. Might be worth making a separate one for the route-agnostic stuff

If it's not too complicated, I'd like to have visits_before/after/between RPCs that omit the `route` parameter, and return all visits to that station regardless of route.

**Comment by faultyserver** [comment]
If the dual-map implementation from #1 is happening, this will be very straight forward:

  - When the route parameter is given, use the `route-trip-station-visit` map to get consecutive visits to the station on the route.
  - When the route parameter is omitted, use the `station-route-trip-visit` map to get all consecutive visits to a station, regardless of route.

**Comment by faultyserver** [comment]
@elliottwilliams As I'm thinking about implementing this, is there any need/would there be a benefit to shipping other information about a Visit in the response?

At this point, the only information getting returned from a `visits_*` call is `[(ETA, ETD),...]`. I think this was originally decided upon because we thought all of those visits would be for the same stop/route/trip. If that condition is no longer true, I could see it being useful to pass more information along.

**Comment by faultyserver** [comment]
The dual-map solution is definitely overkill for most use cases. The performance of the single map is not significantly different between route-oriented and route-agnostic calls. Because of that, it would really just be a waste of memory to create a second map for a neglible performance improvement.

**Comment by faultyserver** [comment]
While this issue has been handled by #5 and #7, I'm going to leave this open until all of the RPCs are implemented in this manner.

**Comment by faultyserver** [comment]
Implemented by 447a2df.
